name: 'Helm tool installer'
description: 'Install a specific version of helm binary. Acceptable values are latest or any semantic version string like 1.15.0'
inputs:
   version:
      description: 'Version of helm'
      required: true
      default: 'latest'
   token:
      description: GitHub token.
      required: false
      deprecationMessage: 'This input is deprecated. Action does not require a token anymore.'
   downloadBaseURL:
      description: 'Set the download base URL'
      required: false
      default: 'https://get.helm.sh'
outputs:
   helm-path:
      description: 'Path to the cached helm binary'
branding:
   color: 'blue'
runs:
   using: 'node20'
   main: 'lib/index.js'
