name: release Project

on:
   push:
      branches:
         - main
      paths:
         - CHANGELOG.md
   workflow_dispatch:

jobs:
   release:
      permissions:
         actions: read
         contents: write
      uses: Azure/action-release-workflows/.github/workflows/release_js_project.yaml@074d812926f43e21038fb170ba2f4bc4e8111503
      with:
         changelogPath: ./CHANGELOG.md
