name: Release Project

on:
   push:
      branches:
         - main
      paths:
         - CHANGELOG.md
   workflow_dispatch:

jobs:
   release:
      permissions:
         actions: read
         contents: write
      uses: Azure/action-release-workflows/.github/workflows/release_js_project.yaml@1b199cc979febcb43526d33853f2d71183091cdb # v1.0.2
      with:
         changelogPath: ./CHANGELOG.md
