name: Create release PR

on:
   workflow_dispatch:
      inputs:
         release:
            description: 'Define release version (ex: v1, v2, v3)'
            required: true

jobs:
   release-pr:
      uses: Azure/action-release-workflows/.github/workflows/release_js_project.yaml@a705b2ab6a3ee889f2b0d925ad0bd2f9eb733ce6
      with:
         release: ${{ github.event.inputs.release }}
